export const AllTypesProps = {
	Query:{
		jobs:{
			input:{
				type:"JobsInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		job:{
			input:{
				type:"JobInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		locations:{
			input:{
				type:"LocationsInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		city:{
			input:{
				type:"LocationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		country:{
			input:{
				type:"LocationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		remote:{
			input:{
				type:"LocationInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	JobsInput:{
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Job:{
		cities:{
			where:{
				type:"CityWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"CityOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		countries:{
			where:{
				type:"CountryWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"CountryOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		remotes:{
			where:{
				type:"RemoteWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"RemoteOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		tags:{
			where:{
				type:"TagWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"TagOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Commitment:{
		jobs:{
			where:{
				type:"JobWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"JobOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	JobWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		title_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		title_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		commitment:{
			type:"CommitmentWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		cities_every:{
			type:"CityWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		cities_some:{
			type:"CityWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		cities_none:{
			type:"CityWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		countries_every:{
			type:"CountryWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		countries_some:{
			type:"CountryWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		countries_none:{
			type:"CountryWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		remotes_every:{
			type:"RemoteWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		remotes_some:{
			type:"RemoteWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		remotes_none:{
			type:"RemoteWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		description_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		description_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		applyUrl_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		applyUrl_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		applyUrl_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		company:{
			type:"CompanyWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags_every:{
			type:"TagWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags_some:{
			type:"TagWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags_none:{
			type:"TagWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		isPublished:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		isPublished_not:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		isFeatured:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		isFeatured_not:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		locationNames_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		locationNames_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		locationNames_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		userEmail_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		userEmail_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		userEmail_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		postedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		postedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		postedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		postedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		postedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		postedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		postedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		postedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"JobWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"JobWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"JobWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CommitmentWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		title_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		title_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_every:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_some:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_none:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"CommitmentWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"CommitmentWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"CommitmentWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	DateTime: "String",
	CityWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		country:{
			type:"CountryWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		type_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		type_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_every:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_some:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_none:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"CityWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"CityWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"CityWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CountryWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		type_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		type_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		isoCode_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		isoCode_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		isoCode_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		cities_every:{
			type:"CityWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		cities_some:{
			type:"CityWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		cities_none:{
			type:"CityWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_every:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_some:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_none:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"CountryWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"CountryWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"CountryWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	RemoteWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		type_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		type_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_every:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_some:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_none:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"RemoteWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"RemoteWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"RemoteWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	CompanyWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		websiteUrl_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		websiteUrl_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		websiteUrl_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		logoUrl_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		logoUrl_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		logoUrl_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_every:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_some:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_none:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		twitter_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		twitter_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		twitter_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailed:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailed_not:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"CompanyWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"CompanyWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"CompanyWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	TagWhereInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_not_in:{
			type:"ID",
			array:true,
			arrayRequired:false,
			required:true
		},
		id_lt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_lte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gt:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_gte:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_contains:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_starts_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		id_not_ends_with:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		name_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_not_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		slug_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		slug_not_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_every:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_some:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		jobs_none:{
			type:"JobWhereInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_not:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_not_in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		updatedAt_lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		updatedAt_gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		AND:{
			type:"TagWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"TagWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"TagWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	JobOrderByInput: "enum",
	CityOrderByInput: "enum",
	City:{
		jobs:{
			where:{
				type:"JobWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"JobOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Country:{
		cities:{
			where:{
				type:"CityWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"CityOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		jobs:{
			where:{
				type:"JobWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"JobOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	CountryOrderByInput: "enum",
	RemoteOrderByInput: "enum",
	Remote:{
		jobs:{
			where:{
				type:"JobWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"JobOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Company:{
		jobs:{
			where:{
				type:"JobWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"JobOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	TagOrderByInput: "enum",
	Tag:{
		jobs:{
			where:{
				type:"JobWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"JobOrderByInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			before:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			last:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	JobInput:{
		companySlug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		jobSlug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	LocationsInput:{
		value:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	LocationInput:{
		slug:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	Mutation:{
		subscribe:{
			input:{
				type:"SubscribeInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		postJob:{
			input:{
				type:"PostJobInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateJob:{
			input:{
				type:"UpdateJobInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			adminSecret:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		updateCompany:{
			input:{
				type:"UpdateCompanyInput",
				array:false,
				arrayRequired:false,
				required:true
			},
			adminSecret:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	SubscribeInput:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	PostJobInput:{
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		commitmentId:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		companyName:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		locationNames:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		userEmail:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		applyUrl:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateJobInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	UpdateCompanyInput:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:true
		},
		logoUrl:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	}
}

export const ReturnTypes = {
	Query:{
		jobs:"Job",
		job:"Job",
		locations:"Location",
		city:"City",
		country:"Country",
		remote:"Remote",
		commitments:"Commitment",
		cities:"City",
		countries:"Country",
		remotes:"Remote",
		companies:"Company"
	},
	Job:{
		id:"ID",
		title:"String",
		slug:"String",
		commitment:"Commitment",
		cities:"City",
		countries:"Country",
		remotes:"Remote",
		description:"String",
		applyUrl:"String",
		company:"Company",
		tags:"Tag",
		isPublished:"Boolean",
		isFeatured:"Boolean",
		locationNames:"String",
		userEmail:"String",
		postedAt:"DateTime",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	Commitment:{
		id:"ID",
		title:"String",
		slug:"String",
		jobs:"Job",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	City:{
		id:"ID",
		name:"String",
		slug:"String",
		country:"Country",
		type:"String",
		jobs:"Job",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	Country:{
		id:"ID",
		name:"String",
		slug:"String",
		type:"String",
		isoCode:"String",
		cities:"City",
		jobs:"Job",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	Remote:{
		id:"ID",
		name:"String",
		slug:"String",
		type:"String",
		jobs:"Job",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	Company:{
		id:"ID",
		name:"String",
		slug:"String",
		websiteUrl:"String",
		logoUrl:"String",
		jobs:"Job",
		twitter:"String",
		emailed:"Boolean",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	Tag:{
		id:"ID",
		name:"String",
		slug:"String",
		jobs:"Job",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	},
	Location:{
		id:"ID",
		slug:"String",
		name:"String",
		type:"String"
	},
	Mutation:{
		subscribe:"User",
		postJob:"Job",
		updateJob:"Job",
		updateCompany:"Company"
	},
	User:{
		id:"ID",
		name:"String",
		email:"String",
		subscribe:"Boolean",
		createdAt:"DateTime",
		updatedAt:"DateTime"
	}
}


export class GraphQLError extends Error {
    constructor(response) {
      super("");
      this.response = response;
      console.error(response);
    }
    toString() {
      return "GraphQL Response Error";
    }
  }



export const ScalarResolver = (scalar, value) => {
  switch (scalar) {
    case 'String':
      return  `${JSON.stringify(value)}`;
    case 'Int':
      return `${value}`;
    case 'Float':
      return `${value}`;
    case 'Boolean':
      return `${value}`;
    case 'ID':
      return `"${value}"`;
    case 'enum':
      return `${value}`;
    case 'scalar':
      return `${value}`;
    default:
      return false;
  }
};  


export const TypesPropsResolver = ({
    value,
    type,
    name,
    key,
    blockArrays
}) => {
    if (value === null) {
        return `null`;
    }
    let resolvedValue = AllTypesProps[type][name];
    if (key) {
        resolvedValue = resolvedValue[key];
    }
    if (!resolvedValue) {
        throw new Error(`Cannot resolve ${type} ${name}${key ? ` ${key}` : ''}`)
    }
    const typeResolved = resolvedValue.type;
    const isArray = resolvedValue.array;
    const isArrayRequired = resolvedValue.arrayRequired;
    if (typeof value === 'string' && value.startsWith(`ZEUS_VAR$`)) {
        const isRequired = resolvedValue.required ? '!' : '';
        let t = `${typeResolved}`;
        if (isArray) {
          if (isRequired) {
              t = `${t}!`;
          }
          t = `[${t}]`;
          if(isArrayRequired){
            t = `${t}!`;
          }
        }else{
          if (isRequired) {
                t = `${t}!`;
          }
        }
        return `\$${value.split(`ZEUS_VAR$`)[1]}__ZEUS_VAR__${t}`;
    }
    if (isArray && !blockArrays) {
        return `[${value
        .map((v) => TypesPropsResolver({ value: v, type, name, key, blockArrays: true }))
        .join(',')}]`;
    }
    const reslovedScalar = ScalarResolver(typeResolved, value);
    if (!reslovedScalar) {
        const resolvedType = AllTypesProps[typeResolved];
        if (typeof resolvedType === 'object') {
        const argsKeys = Object.keys(resolvedType);
        return `{${argsKeys
            .filter((ak) => value[ak] !== undefined)
            .map(
            (ak) => `${ak}:${TypesPropsResolver({ value: value[ak], type: typeResolved, name: ak })}`
            )}}`;
        }
        return ScalarResolver(AllTypesProps[typeResolved], value);
    }
    return reslovedScalar;
};


const isArrayFunction = (
  parent,
  a
) => {
  const [values, r] = a;
  const [mainKey, key, ...keys] = parent;
  const keyValues = Object.keys(values).filter((k) => typeof values[k] !== 'undefined');

  if (!keys.length) {
      return keyValues.length > 0
        ? `(${keyValues
            .map(
              (v) =>
                `${v}:${TypesPropsResolver({
                  value: values[v],
                  type: mainKey,
                  name: key,
                  key: v
                })}`
            )
            .join(',')})${r ? traverseToSeekArrays(parent, r) : ''}`
        : traverseToSeekArrays(parent, r);
    }

  const [typeResolverKey] = keys.splice(keys.length - 1, 1);
  let valueToResolve = ReturnTypes[mainKey][key];
  for (const k of keys) {
    valueToResolve = ReturnTypes[valueToResolve][k];
  }

  const argumentString =
    keyValues.length > 0
      ? `(${keyValues
          .map(
            (v) =>
              `${v}:${TypesPropsResolver({
                value: values[v],
                type: valueToResolve,
                name: typeResolverKey,
                key: v
              })}`
          )
          .join(',')})${r ? traverseToSeekArrays(parent, r) : ''}`
      : traverseToSeekArrays(parent, r);
  return argumentString;
};


const resolveKV = (k, v) =>
  typeof v === 'boolean' ? k : typeof v === 'object' ? `${k}{${objectToTree(v)}}` : `${k}${v}`;


const objectToTree = (o) =>
  `{${Object.keys(o).map((k) => `${resolveKV(k, o[k])}`).join(' ')}}`;


const traverseToSeekArrays = (parent, a) => {
  if (!a) return '';
  if (Object.keys(a).length === 0) {
    return '';
  }
  let b = {};
  if (Array.isArray(a)) {
    return isArrayFunction([...parent], a);
  } else {
    if (typeof a === 'object') {
      Object.keys(a)
        .filter((k) => typeof a[k] !== 'undefined')    
        .map((k) => {
        if (k === '__alias') {
          Object.keys(a[k]).map((aliasKey) => {
            const aliasOperations = a[k][aliasKey];
            const aliasOperationName = Object.keys(aliasOperations)[0];
            const aliasOperation = aliasOperations[aliasOperationName];
            b[
              `${aliasOperationName}__alias__${aliasKey}: ${aliasOperationName}`
            ] = traverseToSeekArrays([...parent, aliasOperationName], aliasOperation);
          });
        } else {
          b[k] = traverseToSeekArrays([...parent, k], a[k]);
        }
      });
    } else {
      return '';
    }
  }
  return objectToTree(b);
};  


const buildQuery = (type, a) =>
  traverseToSeekArrays([type], a)  


const inspectVariables = (query) => {
  const regex = /\$\b\w*__ZEUS_VAR__\[?[^!^\]^\s^,^\)^\}]*[!]?[\]]?[!]?/g;
  let result;
  const AllVariables = [];
  while ((result = regex.exec(query))) {
    if (AllVariables.includes(result[0])) {
      continue;
    }
    AllVariables.push(result[0]);
  }
  if (!AllVariables.length) {
    return query;
  }
  let filteredQuery = query;
  AllVariables.forEach((variable) => {
    while (filteredQuery.includes(variable)) {
      filteredQuery = filteredQuery.replace(variable, variable.split('__ZEUS_VAR__')[0]);
    }
  });
  return `(${AllVariables.map((a) => a.split('__ZEUS_VAR__'))
    .map(([variableName, variableType]) => `${variableName}:${variableType}`)
    .join(', ')})${filteredQuery}`;
};


export const queryConstruct = (t, tName) => (o) => `${t.toLowerCase()}${inspectVariables(buildQuery(tName, o))}`;  


const fullChainConstruct = (fn) => (t,tName) => (o, variables) => fn(queryConstruct(t, tName)(o), variables).then(r => { 
  seekForAliases(r)
  return r
});

export const fullChainConstructor = (
  fn,
  operation,
  key,
) =>
  ((o, variables) => fullChainConstruct(fn)(operation, key)(o, variables))


const fullSubscriptionConstruct = (fn) => (
  t,
  tName,
) => (o, variables) =>
  fn(queryConstruct(t, tName)(o), variables);
  
export const fullSubscriptionConstructor = (
  fn,
  operation,
  key,
) =>
  ((o, variables) => fullSubscriptionConstruct(fn)(operation, key)(o, variables))


const seekForAliases = (o) => {
  const traverseAlias = (value) => {
    if (Array.isArray(value)) {
      value.forEach(seekForAliases);
    } else {
      if (typeof value === 'object') {
        seekForAliases(value);
      }
    }
  };
  if (typeof o === 'object' && o) {
    const keys = Object.keys(o);
    if (keys.length < 1) {
      return;
    }
    keys.forEach((k) => {
      const value = o[k];
      if (k.indexOf('__alias__') !== -1) {
        const [operation, alias] = k.split('__alias__');
        o[alias] = {
          [operation]: value
        };
        delete o[k];
      }
      traverseAlias(value);
    });
  }
};


export const $ = (t) => `ZEUS_VAR$${t.join('')}`;

export const ZeusSelect = () => (t) => t

export const resolverFor = (
  type,
  field,
  fn
) => fn;


const handleFetchResponse = response => {
  if (!response.ok) {
    return new Promise((resolve, reject) => {
      response.text().then(text => {
        try { reject(JSON.parse(text)); }
        catch (err) { reject(text); }
      }).catch(reject);
    });
  }
  return response.json();
};

export const apiFetch = (options) => (query, variables = {}) => {
    const fetchFunction = fetch;
    let queryString = query;
    let fetchOptions = options[1] || {};
    if (fetchOptions.method && fetchOptions.method === 'GET') {
      queryString = encodeURIComponent(query);
      return fetchFunction(`${options[0]}?query=${queryString}`, fetchOptions)
        .then(handleFetchResponse)
        .then((response) => {
          if (response.errors) {
            throw new GraphQLError(response);
          }
          seekForAliases(response.data)
          return response.data;
        });
    }
    return fetchFunction(`${options[0]}`, {
      body: JSON.stringify({ query: queryString, variables }),
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      ...fetchOptions
    })
      .then(handleFetchResponse)
      .then((response) => {
        if (response.errors) {
          throw new GraphQLError(response);
        }
        seekForAliases(response.data)
        return response.data;
      });
  };

export const apiSubscription = (options) => (
    query,
    variables,
  ) => {
    try {
      const queryString = options[0] + '?query=' + encodeURIComponent(query);
      const wsString = queryString.replace('http', 'ws');
      const host = (options.length > 1 && options[1]?.websocket?.[0]) || wsString;
      const webSocketOptions = options[1]?.websocket || [host];
      const ws = new WebSocket(...webSocketOptions);
      return {
        ws,
        on: (e) => {
          ws.onmessage = (event) => {
            if(event.data){
              const parsed = JSON.parse(event.data)
              const data = parsed.data
              if (data) {
                seekForAliases(data);
              }
              return e(data);
            }
          };
        },
        off: (e) => {
          ws.onclose = e;
        },
        error: (e) => {
          ws.onerror = e;
        },
        open: (e) => {
          ws.onopen = e;
        },
      };
    } catch {
      throw new Error('No websockets implemented');
    }
  };

  
export const Thunder = (fn, subscriptionFn) => ({
  query: fullChainConstructor(fn,'query', 'Query'),
mutation: fullChainConstructor(fn,'mutation', 'Mutation')
});

export const Chain = (...options) => ({
  query: fullChainConstructor(apiFetch(options),'query', 'Query'),
mutation: fullChainConstructor(apiFetch(options),'mutation', 'Mutation')
});
export const Zeus = {
  query: (o) => queryConstruct('query', 'Query')(o),
mutation: (o) => queryConstruct('mutation', 'Mutation')(o)
};
export const Cast = {
  query: (o) => (b) => o,
mutation: (o) => (b) => o
};
export const Selectors = {
  query: ZeusSelect(),
mutation: ZeusSelect()
};
    